# theme: jekyll-theme-pages-themes/slate@v0.2.0
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Toko page
email: miura.toko.r8@dc.tohoku.ac.jp
description: >-
  This is a page for Toko Miura.
baseurl: ""
url: "https://toko.github.io"
repository: "yomoginna/toko.github.io"
