# title: Slate theme
# description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

title: Toko page
email: miura.toko.r8@dc.tohoku.ac.jp
description: >-
  This is a page for Toko Miura.
baseurl: ""
url: "https://toko.github.io"
repository: "yomoginna/toko.github.io"