# yamlの記法 https://qiita.com/jerrywdlee/items/d5d31c10617ec7342d56
title: 三浦 東子 
email: miura.toko.r8@dc.tohoku.ac.jp
description: >-
  Toko Miura
# baseurl: "" <- これがあるとremoteでのbuild時にremote_themeが読み込まれないよう? https://stackoverflow.com/questions/48197580/jekyll-theme-does-not-work-on-github-pages-but-works-locally
url: "https://toko.github.io"


show_downloads: true
# google_analytics:
# theme: jekyll-theme-slate # localで試す場合はこちらもwork
# theme: jekyll-theme-dinky
# remote_theme: pages-themes/slate@v0.2.0
remote_theme: pages-themes/dinky@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pwa-plugin
  - jekyll-tagging-related_posts
  - jekyll-target-blank
  - jekyll-postfiles
  - jekyll-og-image

repository: "yomoginna/toko.github.io"



